# Generated by Django 2.0.4 on 2018-04-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sessionlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_privacy',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='skype_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='state_or_country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_id',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='', max_length=100),
        ),
    ]
