# Generated by Django 2.0.4 on 2018-06-24 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180624_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followlog',
            old_name='following',
            new_name='notification_owner',
        ),
        migrations.RenameField(
            model_name='followlog',
            old_name='follower',
            new_name='user',
        ),
    ]
